# Generated by Django 4.1.3 on 2022-11-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=True, max_length=30, null=True)),
                ('mobile_number', models.CharField(default=True, max_length=15, null=True)),
                ('password', models.CharField(default=True, max_length=20, null=True)),
                ('confirm_password', models.CharField(default=True, max_length=20, null=True)),
                ('fname', models.CharField(default=True, max_length=30, null=True)),
                ('lname', models.CharField(default=True, max_length=20, null=True)),
                ('dob', models.DateField(default=True, null=True)),
                ('email', models.EmailField(default=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Searchflight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(default=True, max_length=30, null=True)),
                ('arrival', models.CharField(default=True, max_length=30, null=True)),
                ('date', models.DateField(default=True, max_length=30, null=True)),
                ('return_date', models.DateTimeField(default=True, max_length=30, null=True)),
                ('cabin_class', models.CharField(default=True, max_length=30, null=True)),
            ],
        ),
    ]
