# Generated by Django 4.1.3 on 2022-11-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_no_of_seats', models.IntegerField(default=True, null=True)),
                ('no_of_seats_reserved', models.IntegerField(default=True, null=True)),
                ('week_availability', models.CharField(default=True, max_length=30, null=True)),
                ('flight_numbers', models.IntegerField(default=True, null=True)),
                ('depaturedatetime', models.DateTimeField()),
                ('arrivaldatatime', models.DateTimeField()),
                ('return_datetime', models.DateTimeField(default=True, null=True)),
                ('fare', models.FloatField(default=True)),
            ],
        ),
    ]
