# Generated by Django 4.1.3 on 2022-11-22 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_reservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
