# Generated by Django 4.1.3 on 2022-11-22 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myaccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.reservation')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_date', to='booking.searchflight')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_place', to='booking.searchflight')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.enrollment')),
                ('fname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Myaccount', to='booking.enrollment')),
                ('lname', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, related_name='lastname', to='booking.enrollment')),
                ('sourse', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, related_name='departure_place', to='booking.searchflight')),
            ],
        ),
    ]
