# Generated by Django 4.1.3 on 2022-11-23 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_myaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_of_flight', models.CharField(default=True, max_length=30, null=True)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('arrival_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.searchflight')),
                ('departure_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_city', to='booking.searchflight')),
                ('flight_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.reservation')),
            ],
        ),
    ]
